// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPackage(arg1:string):Promise<void>;

export function CheckBunInstalled():Promise<string>;

export function EnsureRunnerProject():Promise<void>;

export function FindBunPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallBun():Promise<void>;

export function InstallBunFlow():Promise<void>;

export function ListInstalledPackages():Promise<Array<main.PackageInfo>>;

export function ListPackages(arg1:boolean):Promise<string>;

export function PromptInstallBun():Promise<boolean>;

export function RemovePackage(arg1:string):Promise<void>;

export function RunJS(arg1:string):Promise<main.RunResult>;

export function StartUpdateChecker():Promise<void>;
