// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPackage(arg1) {
  return window['go']['main']['App']['AddPackage'](arg1);
}

export function CheckBunInstalled() {
  return window['go']['main']['App']['CheckBunInstalled']();
}

export function EnsureRunnerProject() {
  return window['go']['main']['App']['EnsureRunnerProject']();
}

export function FindBunPath() {
  return window['go']['main']['App']['FindBunPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallBun() {
  return window['go']['main']['App']['InstallBun']();
}

export function InstallBunFlow() {
  return window['go']['main']['App']['InstallBunFlow']();
}

export function ListInstalledPackages() {
  return window['go']['main']['App']['ListInstalledPackages']();
}

export function ListPackages(arg1) {
  return window['go']['main']['App']['ListPackages'](arg1);
}

export function PromptInstallBun() {
  return window['go']['main']['App']['PromptInstallBun']();
}

export function RemovePackage(arg1) {
  return window['go']['main']['App']['RemovePackage'](arg1);
}

export function RunJS(arg1) {
  return window['go']['main']['App']['RunJS'](arg1);
}

export function StartUpdateChecker() {
  return window['go']['main']['App']['StartUpdateChecker']();
}
